version : "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockerdb
      - POSTGRES_DB=dev
    volumes:
      - pgdata:/data/postgres

  db:
    image: postgres
    restart: always
    container_name: integration-test-prisma
    ports:
    - 5433:5432
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=test

volumes:
  pgdata:
    driver: local